name: Publish NPM

on:
  release:
    types: [created]
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install
        run: npm ci
      - name: Bundle
        run: npm run bundle --if-present
      - name: lint
        run: npm run lint
      - name: Test
        run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
      - name: Install
        run: npm ci
      - name: Bundle
        run: npm run bundle --if-present
      - name: Publish
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npm run release
      - name: Clean Up
        run: rm .npmrc
